add TCP dialTimeout logs
jcmturner/gokrb5 pull request #453
Opened 2021-11-29 14:48 UTC by chandanjainn

- In `dialKDCTCP`  method we have just printed up addtional information that gives us exact network error that is thrown.
- Whenever we have a machine downtime we are not able to identify the exact machine that is down as we have the KDC IP being dynamically assigned by an automation script. 
- Any error thrown by `DialTimeout` method on line 104 are not captured anywhere but a generic statement on line 121 without any detailed information. The fix added returns error strings with details about the issue especially the IP address of the machine/KDC server. 
- The below is example of how the logs will be printed
`DialTimeout:  dial tcp 10.128.41.183:88: i/o timeout`

2022-06-15 12:23 UTC, chandanjainn commented
@jcmturner can we get this reviewed and merged please?

2022-07-15 21:53 UTC, jcmturner requested changes
Looks good I think we need something similar on dialSendUDP function as well. Would you mind adding that too?

2022-07-17 10:16 UTC, chandanjainn commented
> Looks good I think we need something similar on dialSendUDP function as well. Would you mind adding that too?

@jcmturner done.

2022-07-17 13:05 UTC, jcmturner requested changes

2022-07-17 13:05 UTC, jcmturner commented on v8/client/network.go
>  	return nil, fmt.Errorf("error sending to a KDC: %s", strings.Join(errs, "; "))
Sorry for not spotting this earlier. Seems like the dialSendUdp() function was already handling this. Perhaps the best fix is to adopt this style of handling it in the TCP equivalent.

2022-07-17 14:46 UTC, chandanjainn commented
@jcmturner removed the changes for sendDialUDP. even I missed that it was already handled :)

2022-07-17 19:27 UTC, jcmturner requested changes

2022-07-17 19:27 UTC, jcmturner commented on v8/client/network.go
>  	return nil, errors.New("error in getting a TCP connection to any of the KDCs")
I'm suggesting we make this line `return nil, fmt.Errorf("error sending to a KDC: %s", strings.Join(errs, "; "))
` so this is consistent with the UDP function. Then we don't need the if statement and the lines within.

2022-07-18 04:43 UTC, chandanjainn commented
@jcmturner done.

2022-07-18 05:33 UTC, jcmturner approved these changes

2022-07-18 05:53 UTC, jcmturner approved these changes

2022-07-18 06:01 UTC, chandanjainn commented
@jcmturner checks have passed. can we merge and close this?

2022-07-18 06:15 UTC, merged

2022-07-18 06:15 UTC, jcmturner commented
Thanks for the contribution!